---
title: "Automatic detection of dec (. or ,) #4482"
author: "Doris Amoakohene"
date: "`r Sys.Date()`"
output: html_document
---




```{r}
# automatic detection of dec=',' for #2431
DT = data.table(a = letters, b = 1:26/6, c = 1:26)
## auto-detect dec=','
fwrite(DT, f <- tempfile(), dec=',', sep=';')
test(2253.1, fread(f), DT)

fwrite(DT, f, dec=',', sep='|')
test(2253.2, fread(f), DT)

## auto-detect dec='.'
fwrite(DT, f)
test(2253.3, fread(f), DT)

## verbose output
test(2253.4, fread(f, verbose=TRUE), DT, output="sep=',' so dec set to '.'")

fwrite(DT, f, dec=',', sep=';')
test(2253.5, fread(f, verbose=TRUE), DT, output="dec=',' detected based on a balance of 18")
test(2253.6, fread('a;b\n1,14;5', verbose=TRUE), data.table(a=1.14, b=5L), output="dec=',' detected based on a balance of 1 ")
```












```{r}

library(atime)
library(ggplot2)
library(data.table)

```

```{r}
  tdir <- tempfile()
  dir.create(tdir)
  git2r::clone("https://github.com/Rdatatable/data.table", tdir)
  
```









```{r}

atime.list.4482 <- atime::atime_versions(
pkg.path=tdir,
pkg.edit.fun=function(old.Package, new.Package, sha, new.pkg.path){
      pkg_find_replace <- function(glob, FIND, REPLACE){
        atime::glob_find_replace(file.path(new.pkg.path, glob), FIND, REPLACE)
      }
      Package_regex <- gsub(".", "_?", old.Package, fixed=TRUE)
      Package_ <- gsub(".", "_", old.Package, fixed=TRUE)
      new.Package_ <- paste0(Package_, "_", sha)
      pkg_find_replace(
        "DESCRIPTION", 
        paste0("Package:\\s+", old.Package),
        paste("Package:", new.Package))
      pkg_find_replace(
        file.path("src","Makevars.*in"),
        Package_regex,
        new.Package_)
      pkg_find_replace(
        file.path("R", "onLoad.R"),
        Package_regex,
        new.Package_)
      pkg_find_replace(
        file.path("R", "onLoad.R"),
        sprintf('packageVersion\\("%s"\\)', old.Package),
        sprintf('packageVersion\\("%s"\\)', new.Package))
      pkg_find_replace(
        file.path("src", "init.c"),
        paste0("R_init_", Package_regex),
        paste0("R_init_", gsub("[.]", "_", new.Package_)))
      pkg_find_replace(
        "NAMESPACE",
        sprintf('useDynLib\\("?%s"?', Package_regex),
        paste0('useDynLib(', new.Package_))
    },

  N=10^seq(1,20),
  setup={ 
    set.seed(108)
    df <- data.frame(x = runif(N))
    dt <- as.data.table(df)
    
  },

  expr=data.table:::`[.data.table`(transform(dt, y = round(x))),
"Before"="19b7866112614db53eb3e909c097407d91cd6738",#parent of the regression commit (https://github.com/Rdatatable/data.table/commit/0895fa247afcf6b38044bd5f56c0d209691ddb31), which is the parent of the first commit in the PR that causes the issue (https://github.com/Rdatatable/data.table/pull/5493/commits) 

  "Regression"="0895fa247afcf6b38044bd5f56c0d209691ddb31", #The regression commit is parent of the first commit in the PR that fixes the issue  (https://github.com/Rdatatable/data.table/pull/5493/commits)

  "Fixed"="1e03fe7b890e63da9651d997ea52548c90b3ae32")# last commit of the PR that fixes the issue (https://github.com/Rdatatable/data.table/pull/5493/commits)
```






```{r}
plot(atime.list.4482)+
  labs(title = "Automatic detection of dec (. or ,) #4482")

png("atime.list.4482.png")
plot(atime.list.4482)+
  labs(title = "Automatic detection of dec (. or ,) #4482")
dev.off()

```



```

