---
title: "Remove deep copy of indices from shallow()"
author: "Doris Amoakohene"
date: "`r Sys.Date()`"
output: html_document
---

Remove deep copy of indices from shallow() #4440
https://github.com/Rdatatable/data.table/pull/4440
https://github.com/Rdatatable/data.table/commits/master?after=db5ba4135ffb95dca6d43f115c34c5786147c3ba+454&branch=master&qualified_name=refs%2Fheads%2Fmaster

https://github.com/DorisAmoakohene/data.table/commit/b636fcde8e7bef2ff50e4fc54d7d3a7332dde6ee
```{r}

library(atime)
library(data.table)
library(ggplot2)
library(git2r)

```



```{r}
  tdir <- tempfile()
  dir.create(tdir)
  git2r::clone("https://github.com/Rdatatable/data.table", tdir)
  
```

```{r}

atime.list.4440 <- atime::atime_versions(
pkg.path= "C:\\Users\\amoak\\mydata.table",
pkg.edit.fun=function(old.Package, new.Package, sha, new.pkg.path){
      pkg_find_replace <- function(glob, FIND, REPLACE){
        atime::glob_find_replace(file.path(new.pkg.path, glob), FIND, REPLACE)
      }
      Package_regex <- gsub(".", "_?", old.Package, fixed=TRUE)
      Package_ <- gsub(".", "_", old.Package, fixed=TRUE)
      new.Package_ <- paste0(Package_, "_", sha)
      pkg_find_replace(
        "DESCRIPTION", 
        paste0("Package:\\s+", old.Package),
        paste("Package:", new.Package))
      pkg_find_replace(
        file.path("src","Makevars.*in"),
        Package_regex,
        new.Package_)
      pkg_find_replace(
        file.path("R", "onLoad.R"),
        Package_regex,
        new.Package_)
      pkg_find_replace(
        file.path("R", "onLoad.R"),
        sprintf('packageVersion\\("%s"\\)', old.Package),
        sprintf('packageVersion\\("%s"\\)', new.Package))
      pkg_find_replace(
        file.path("src", "init.c"),
        paste0("R_init_", Package_regex),
        paste0("R_init_", gsub("[.]", "_", new.Package_)))
      pkg_find_replace(
        "NAMESPACE",
        sprintf('useDynLib\\("?%s"?', Package_regex),
        paste0('useDynLib(', new.Package_))
    },

  N= 10^seq(3,8),
  setup={
    set.seed(1L)
    dt <- data.table(
      a=sample(N,N))
    setindex(dt, a)
  },

  expr=data.table:::shallow(dt),
  #"Before"="",
#This is a three code branch issue but before  cannot be found, 
  "Regression"="b1b1832b0d2d4032b46477d9fe6efb15006664f4", 
#parent of the first commits in the PR that fixes the regression(https://github.com/Rdatatable/data.table/commit/0f0e7127b880df8459b0ed064dc841acd22f5b73)
  "Fixed"="40f9165a265f68b87ffb3cb00efbaa9540c2dcb8")# commit "Merge branch 'master' into tuning_shallow in the PR that fixes the regression" (https://github.com/Rdatatable/data.table/pull/4440/commits)


```


Remove deep copy of indices from shallow() #4440
```{r}
plot(atime.list.4440)+
  labs(title = "Remove deep copy of indices from shallow #4440")

png("atime.list.4440.png")
plot(atime.list.4440)+
  labs(title = "Remove deep copy of indices from shallow #4440")
dev.off()

```




















































```{r}
atime.list.sys.4440 <- atime::atime_versions(
pkg.path=tdir,
pkg.edit.fun=function(old.Package, new.Package, sha, new.pkg.path){
      pkg_find_replace <- function(glob, FIND, REPLACE){
        atime::glob_find_replace(file.path(new.pkg.path, glob), FIND, REPLACE)
      }
      Package_regex <- gsub(".", "_?", old.Package, fixed=TRUE)
      Package_ <- gsub(".", "_", old.Package, fixed=TRUE)
      new.Package_ <- paste0(Package_, "_", sha)
      pkg_find_replace(
        "DESCRIPTION", 
        paste0("Package:\\s+", old.Package),
        paste("Package:", new.Package))
      pkg_find_replace(
        file.path("src","Makevars.*in"),
        Package_regex,
        new.Package_)
      pkg_find_replace(
        file.path("R", "onLoad.R"),
        Package_regex,
        new.Package_)
      pkg_find_replace(
        file.path("R", "onLoad.R"),
        sprintf('packageVersion\\("%s"\\)', old.Package),
        sprintf('packageVersion\\("%s"\\)', new.Package))
      pkg_find_replace(
        file.path("src", "init.c"),
        paste0("R_init_", Package_regex),
        paste0("R_init_", gsub("[.]", "_", new.Package_)))
      pkg_find_replace(
        "NAMESPACE",
        sprintf('useDynLib\\("?%s"?', Package_regex),
        paste0('useDynLib(', new.Package_))
    },
  N= 10^seq(3,8),
  setup={
    dt1 <- data.table(a = sample(N,N))
    set.seed(123L)
    dt2 <- data.table(
      a=sample(N,N))
    setindex(dt2, a)
  },
  expr= function(dt1, dt2) {
    result <- NULL
    for (i in seq_len(N)) {
      result <- rbindlist(list(result, fintersect(dt2, dt1)))
    }
    result
  },
  "Before"="ad7b67c80a551b7a1e2ef8b73d6162ed7737c934",
#https://github.com/Rdatatable/data.table/commit/ad7b67c80a551b7a1e2ef8b73d6162ed7737c934
  "Regression"="dd7609e83132e19c9be80d71c73e8a8f95e19b27", 
#https://github.com/Rdatatable/data.table/tree/752012f577f8e268bb6d0084ca39a09fa7fbc1c4
  "Fixed"="9d3b9202fddb980345025a4f6ac451ed26a423be")#https://github.com/Rdatatable/data.table/commit/9d3b9202fddb980345025a4f6ac451ed26a423be 
```



```{r}
plot(atime.list.sys.4440)

plot(atime.list.sys.4440)

png("atime.list.sys.4440.png")
plot(atime.list.sys.4440)
dev.off()
```


```{r}
atime.list.sys.4440 <- atime::atime_versions(
pkg.path=tdir,
pkg.edit.fun=function(old.Package, new.Package, sha, new.pkg.path){
      pkg_find_replace <- function(glob, FIND, REPLACE){
        atime::glob_find_replace(file.path(new.pkg.path, glob), FIND, REPLACE)
      }
      Package_regex <- gsub(".", "_?", old.Package, fixed=TRUE)
      Package_ <- gsub(".", "_", old.Package, fixed=TRUE)
      new.Package_ <- paste0(Package_, "_", sha)
      pkg_find_replace(
        "DESCRIPTION", 
        paste0("Package:\\s+", old.Package),
        paste("Package:", new.Package))
      pkg_find_replace(
        file.path("src","Makevars.*in"),
        Package_regex,
        new.Package_)
      pkg_find_replace(
        file.path("R", "onLoad.R"),
        Package_regex,
        new.Package_)
      pkg_find_replace(
        file.path("R", "onLoad.R"),
        sprintf('packageVersion\\("%s"\\)', old.Package),
        sprintf('packageVersion\\("%s"\\)', new.Package))
      pkg_find_replace(
        file.path("src", "init.c"),
        paste0("R_init_", Package_regex),
        paste0("R_init_", gsub("[.]", "_", new.Package_)))
      pkg_find_replace(
        "NAMESPACE",
        sprintf('useDynLib\\("?%s"?', Package_regex),
        paste0('useDynLib(', new.Package_))
    },
#https://github.com/Rdatatable/data.table/issues/4311#issue-584883821,link to code setup
  N= 10^seq(3,8),
  setup={
   dt <- data.table(symbol = rep(1:1000, each = 5000))
    dt[, date := seq_len(.N), by = symbol]
    setkeyv(dt, c("symbol", "date"))
    flag_dt <- data.table(symbol = sample.int(500, 5000, replace = TRUE))
    flag_dt[, start_date := sample.int(3000, .N, replace = TRUE)]
    flag_dt[, end_date := start_date + sample.int(3000, .N, replace = TRUE)]
    flag_dt[, id := seq_len(.N)]
    calendar <- dt[, sort(unique(date))]
    dt[, flag0 := sample(0:1, .N, replace = TRUE)]
    setindexv(dt, "flag0")
  },
#system.time({
  #dt[, flag := 0L]
  #flag_dt[, {
   # dates <- calendar[calendar %between% c(start_date, end_date)]
    #if (length(dates)) {
     # selector <- list(symbol, dates)
      #dt[selector, flag := 1L]
    #}
    #NULL
  #}, by = id]
#})
  expr=data.table:::`[.data.table`(dt,
      ,
      (flag := 0L),
      flag_dt[, {
        dates <- calendar[calendar %between% c(start_date, end_date)]
        if (length(dates)) {
          selector <- list(symbol, dates)
          dt[selector, flag := 1L]
        }
        NULL
      }, by = id]
),
  "Before"="ad7b67c80a551b7a1e2ef8b73d6162ed7737c934",
#https://github.com/Rdatatable/data.table/commit/ad7b67c80a551b7a1e2ef8b73d6162ed7737c934
  "Regression"="752012f577f8e268bb6d0084ca39a09fa7fbc1c4", 
#https://github.com/Rdatatable/data.table/tree/752012f577f8e268bb6d0084ca39a09fa7fbc1c4
  "Fixed"="9d3b9202fddb980345025a4f6ac451ed26a423be")#https://github.com/Rdatatable/data.table/commit/9d3b9202fddb980345025a4f6ac451ed26a423be 
```




