---
title: '[[ by group performance #4655'
output: html_document
date: "2024-02-15"
---




```{r}
library(atime)
library(ggplot2)
library(data.table)
```


```{r}

  tdir <- tempfile()
  dir.create(tdir)
  git2r::clone("https://github.com/Rdatatable/data.table", tdir)
  
```




```{r}
atime.list.4646 <- atime::atime_versions(
  pkg.path=tdir,
  pkg.edit.fun=function(old.Package, new.Package, sha, new.pkg.path){
    pkg_find_replace <- function(glob, FIND, REPLACE){
      atime::glob_find_replace(file.path(new.pkg.path, glob), FIND, REPLACE)
    }
  Package_regex <- gsub(".", "_?", old.Package, fixed=TRUE)
    Package_ <- gsub(".", "_", old.Package, fixed=TRUE)
    new.Package_ <- paste0(Package_, "_", sha)
    pkg_find_replace(
      "DESCRIPTION",
      paste0("Package:\\s+", old.Package),
      paste("Package:", new.Package))
  pkg_find_replace(
    file.path("src","Makevars.*in"),
    Package_regex,
    new.Package_)
  pkg_find_replace(
    file.path("R", "onLoad.R"),
    Package_regex,
    new.Package_)
  pkg_find_replace(
    file.path("R", "onLoad.R"),
    sprintf('packageVersion\\("%s"\\)', old.Package),
    sprintf('packageVersion\\("%s"\\)', new.Package))
  pkg_find_replace(
    file.path("src", "init.c"),
    paste0("R_init_", Package_regex),
    paste0("R_init_", gsub("[.]", "_", new.Package_)))
  pkg_find_replace(
    "NAMESPACE",
    sprintf('useDynLib\\("?%s"?', Package_regex),
    paste0('useDynLib(', new.Package_))
  },
  N=10^seq(1,7),
  setup={ 
    n_nested = 40L
    dt = data.table(id = seq_len(N),
                    value = replicate(N, data.table(val1 = sample(n_nested)), simplify = FALSE))
  },
  
  expr=data.table:::`[.data.table`(dt, , value[[1L]], by = id),
  #"Before"="e0140eafa07ad39a7ac9d67737cc43c4c95ca935",#This is the commit tag 1.12.8(https://github.com/Rdatatable/data.table/tags)
  "slow"="db618444a4d16b91cccf35d80fa3f306739dd571", #parent of the first commit in the PR that fixes the issue(https://github.com/Rdatatable/data.table/pull/4655/commits)
  "Fast"="ec041f78691f9f9495c0f25b78109cd3f5295f4f") #This is the last commit in the PR that fixes the issue (https://github.com/Rdatatable/data.table/pull/4655/commits)
```


```{r}
plot(atime.list.4646)+
  labs(title = "[[ by group takes forever (24 hours +) with v1.13.0 vs 4 seconds with v1.12.8 #4646")

png("atime.list.4646.png")
plot(atime.list.4646)+
  labs(title = "[[ by group takes forever (24 hours +) with v1.13.0 vs 4 seconds with v1.12.8 #4646")
dev.off()
```


```{r}
atime.list.4658 <- atime::atime_versions(
  pkg.path=tdir,
  pkg.edit.fun=function(old.Package, new.Package, sha, new.pkg.path){
    pkg_find_replace <- function(glob, FIND, REPLACE){
      atime::glob_find_replace(file.path(new.pkg.path, glob), FIND, REPLACE)
    }
    Package_regex <- gsub(".", "_?", old.Package, fixed=TRUE)
    Package_ <- gsub(".", "_", old.Package, fixed=TRUE)
    new.Package_ <- paste0(Package_, "_", sha)
    pkg_find_replace(
      "DESCRIPTION", 
      paste0("Package:\\s+", old.Package),
      paste("Package:", new.Package))
    pkg_find_replace(
      file.path("src","Makevars.*in"),
      Package_regex,
      new.Package_)
    pkg_find_replace(
      file.path("R", "onLoad.R"),
      Package_regex,
      new.Package_)
    pkg_find_replace(
      file.path("R", "onLoad.R"),
      sprintf('packageVersion\\("%s"\\)', old.Package),
      sprintf('packageVersion\\("%s"\\)', new.Package))
    pkg_find_replace(
      file.path("src", "init.c"),
      paste0("R_init_", Package_regex),
      paste0("R_init_", gsub("[.]", "_", new.Package_)))
    pkg_find_replace(
      "NAMESPACE",
      sprintf('useDynLib\\("?%s"?', Package_regex),
      paste0('useDynLib(', new.Package_))
  },
  N=10^seq(1,7),
  setup={ 
    dt <- data.table('id'= N,
                     'list_col'=sample(c('', '', 'a', 'a:b', 'a:b:c'), 20000, TRUE))
    feature <- 'list_col'
  },
  
  expr=data.table:::`[.data.table`(dt[, c("id", feature), with = FALSE][
    , feature_names := {
      x <- get(feature)
      stringr::str_split(x, ':')
    }][
      , .(
        feature_names = paste0(feature, "_", unlist(feature_names))
      )
      , by = "id"]
  , times = 10
  , unit = 'ms'),
  #"Before"="e0140eafa07ad39a7ac9d67737cc43c4c95ca935",#This is the commit tag 1.12.8(https://github.com/Rdatatable/data.table/tags)
  "slow"="db618444a4d16b91cccf35d80fa3f306739dd571", #parent of the first commit in the PR that fixes the issue(https://github.com/Rdatatable/data.table/pull/4655/commits)
  "Fast"="ec041f78691f9f9495c0f25b78109cd3f5295f4f") #This is the last commit in the PR that fixes the issue (https://github.com/Rdatatable/data.table/pull/4655/commits)
```

```{r}
plot(atime.list.4658)+
  labs(title = "1.13.0 slow down in a repeated loop on list column #4658")

png("atime.list.4658.png")
plot(atime.list.4658)+
  labs(title = "1.13.0 slow down in a repeated loop on list column #4658")
dev.off()
```



```{r}

atime.list.4655 <- atime::atime_versions(
  pkg.path=tdir,
  pkg.edit.fun=function(old.Package, new.Package, sha, new.pkg.path){
    pkg_find_replace <- function(glob, FIND, REPLACE){
      atime::glob_find_replace(file.path(new.pkg.path, glob), FIND, REPLACE)
    }
    Package_regex <- gsub(".", "_?", old.Package, fixed=TRUE)
    Package_ <- gsub(".", "_", old.Package, fixed=TRUE)
    new.Package_ <- paste0(Package_, "_", sha)
    pkg_find_replace(
      "DESCRIPTION", 
      paste0("Package:\\s+", old.Package),
      paste("Package:", new.Package))
    pkg_find_replace(
      file.path("src","Makevars.*in"),
      Package_regex,
      new.Package_)
    pkg_find_replace(
      file.path("R", "onLoad.R"),
      Package_regex,
      new.Package_)
    pkg_find_replace(
      file.path("R", "onLoad.R"),
      sprintf('packageVersion\\("%s"\\)', old.Package),
      sprintf('packageVersion\\("%s"\\)', new.Package))
    pkg_find_replace(
      file.path("src", "init.c"),
      paste0("R_init_", Package_regex),
      paste0("R_init_", gsub("[.]", "_", new.Package_)))
    pkg_find_replace(
      "NAMESPACE",
      sprintf('useDynLib\\("?%s"?', Package_regex),
      paste0('useDynLib(', new.Package_))
  },
  N=10^seq(1,7),
  setup={ 
    set.seed(123)
    dt = data.table(ordered_id = seq_len(N),
                    unordered_id = sample(N),
                    value = replicate(N, data.table(val1 = sample(40)), simplify = FALSE))
  },
  
  expr=data.table:::`[.data.table`(dt, , value[[1L]], by = ordered_id),
  #"Before"="e0140eafa07ad39a7ac9d67737cc43c4c95ca935",#This is the commit tag 1.12.8(https://github.com/Rdatatable/data.table/tags)
  "slow"="db618444a4d16b91cccf35d80fa3f306739dd571", #parent of the first commit in the PR that fixes the issue(https://github.com/Rdatatable/data.table/pull/4655/commits)
  "Fast"="ec041f78691f9f9495c0f25b78109cd3f5295f4f") #This is the last commit in the PR that fixes the issue (https://github.com/Rdatatable/data.table/pull/4655/commits)
```


```{r}
plot(atime.list.4655)+
  labs(title = "
[[ by group performance #4655")

png("atime.list.4655.png")
plot(atime.list.4655)+
  labs(title = "
[[ by group performance #4655")
dev.off()

```




